### PR TITLE
 Bump `aeson` from `1.5.*` to `2.0.*`

### PR DESCRIPTION
**Pull request by ReinierMaas**
XRef: https://github.com/channable/vaultenv/issues/118

This is the first try to overwrite the packages such that `stack` can compile with `aeson 2.0.*` available.

This adds a Haskell overlay in the process.

This overwrites the minimal set of packages in the `./nix/haskell-overlay.nix` to enable `aeson 2.0.*`.

---

The current state is that the dependencies compile but the package itself needs to be modified to work with the updated `aeson` package.

```
$ nix run -c stack build
vaultenv-real> build (lib + exe)
Preprocessing library for vaultenv-real-0.14.0..
Building library for vaultenv-real-0.14.0..
Preprocessing executable 'vaultenv' for vaultenv-real-0.14.0..
Building executable 'vaultenv' for vaultenv-real-0.14.0..
[1 of 2] Compiling Main [SecretsFile changed]

/home/reinier/channable/vaultenv/app/Main.hs:156:65: error:
    • Couldn't match type: Data.Aeson.KeyMap.KeyMap Aeson.Value
                     with: HashMap Text Aeson.Value
      Expected: HashMap Text Aeson.Value
        Actual: Aeson.Object
    • In the second argument of ‘mapMaybe’, namely ‘obj’
      In the first argument of ‘MountInfo’, namely
        ‘(mapMaybe (\ v -> parseMaybe getType v) obj)’
      In the second argument of ‘($)’, namely
        ‘MountInfo (mapMaybe (\ v -> parseMaybe getType v) obj)’
    |
156 |         pure $ MountInfo (mapMaybe (\v -> parseMaybe getType v) obj)
    |                                                                 ^^^

--  While building package vaultenv-real-0.14.0 (scroll up to its section to see the error) using:
      /home/reinier/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-3.4.1.0 build lib:vaultenv-real exe:vaultenv --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

```

### CODE REVIEW

**Comment by ReinierMaas** [comment]
I couldn't get static binary to work on this branch so am currently building that on the `master` branch to see if it was working on my machine. I will then work my way up to the GHC migration branch and get it to compile there with the newer stackage LTS version and necessary Hackage snapshot. Later I can try to make it compile with this branch where certain packages are overridden.

**Comment by ReinierMaas** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Merge rejected: the target branch must be the integration branch.

**Comment by ReinierMaas** [comment]
Yes merge bot, I want to merge both branches at once...

**Comment by ReinierMaas** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @ReinierMaas, rebasing now.
